### PR TITLE
Fix #128, strncpy should result in null term

### LINKED ISSUE #128: strncpy possibly not null-terminating
```
/home/user/nasa/cFS/tools/cFS-GroundSystem/Subsystems/cmdUtil/cmdUtil.c:817:17: error: ‘strncpy’ specified bound 1024 equals destination size [-Werror=stringop-truncation]
                 strncpy(sbuf, &tail[1], sizeof(sbuf));
```

https://github.com/nasa/cFS-GroundSystem/blob/5e879b9f9eb4dad353e615449d3baacb8b7fde9b/Subsystems/cmdUtil/cmdUtil.c#L817

### PR DESCRIPTION
**Pull request by CDKnightNASA**
**Describe the contribution**
Closes #128 

Reduce the size of the strncpy so that it ensures there's a null byte at the end of the string buffer.

**Testing performed**
make install, make test

**System(s) tested on**
Debian 10.5

**Contributor Info - All information REQUIRED for consideration of pull request**
Christopher.D.Knight@nasa.gov

### CODE REVIEW

**Comment by astrogeco** [comment]
[CCB 2020-09-02](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-September-02-2020) APPROVED, fix parenthesis

File: Subsystems/cmdUtil/cmdUtil.c [hunk 1]
```diff
@@ -814,7 +814,7 @@ int main(int argc, char *argv[])
                 }
 
                 /* Copy the data over (zero fills) */
-                strncpy(sbuf, &tail[1], sizeof(sbuf));
+                strncpy(sbuf, &tail[1], sizeof(sbuf - 1));
```
Comment (astrogeco) [inline Subsystems/cmdUtil/cmdUtil.c:817]: Fix parenthesis

Comment (CDKnightNASA) [reply Subsystems/cmdUtil/cmdUtil.c]: fixed

**Review by skliper — APPROVED** [review]
